//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuyaSharp.CodeGeneration.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstructionsSetTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstructionsSetTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TuyaSharp.CodeGeneration.Templates.InstructionsSetTemplates", typeof(InstructionsSetTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static Command {{ResolvedCommandName}}Command(bool value)
        ///    {
        ///        return new Command
        ///        {
        ///            Code=&quot;{{commandCode}}&quot;,
        ///            Value=value.ToString(),
        ///            ValueType=&quot;Boolean&quot;
        ///        };
        ///    }
        ///.
        /// </summary>
        internal static string BooleanTemplate {
            get {
                return ResourceManager.GetString("BooleanTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static Command {{ResolvedCommandName}}Command({{Category}}{{ResolvedCommandName}}Enum value)
        ///    {
        ///        return new Command
        ///        {
        ///            Code = &quot;{{commandCode}}&quot;,
        ///            Value = CommandValueAttributeHelper.GetCommandValue(value),
        ///            ValueType = &quot;Enum&quot;
        ///        };
        ///    }
        ///.
        /// </summary>
        internal static string EnumTemplate {
            get {
                return ResourceManager.GetString("EnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static Command {{ResolvedCommandName}}Command(int value)
        ///    {
        ///        if (value is &lt; {{minValue}} or &gt; {{maxValue}}) throw new ArgumentOutOfRangeException(nameof(value), &quot;Value must be between {{minValue}} and {{maxValue}}.&quot;);
        ///
        ///        return new Command
        ///        {
        ///            Code = &quot;{{commandCode}}&quot;,
        ///            Value = value.ToString(),
        ///            ValueType = &quot;Integer&quot;
        ///        };
        ///    }
        ///.
        /// </summary>
        internal static string IntegerTemplate {
            get {
                return ResourceManager.GetString("IntegerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using TuyaSharp.Utils;
        ///using TuyaSharp.Attributes;
        ///using TuyaSharp.DTO.Device.DeviceCommand;
        ///
        ///namespace Generated;
        ///
        /// /*
        ///    Auto-generated code.
        ///*/
        ///
        ///public static class {{Category}}InstructionsSet
        ///{
        ///    #region Methods
        ///    {{Methods}}
        ///    #endregion
        ///
        ///    {{EnumsSectionStart}}
        ///    #region Enums
        ///    {{Enums}}
        ///    #endregion
        ///    {{EnumsSectionEnd}}
        ///}
        ///.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
